### ISSUE TITLE
snapshot dont refresh in picture-card

### ISSUE THREAD

**Issue by jayjojayson** [Phil7989/advanced_snapshot#1]
Hi, thanks for sharing this. 👍 Works really nice, but i have one little problem. I think it is more an HA setting, but i dont know. I want to add the snapshot to a picture card and had setup the path to the snapshot. The snapshot is showing, but i dont get the next snapshot showing. The snapshot dont refresh so to say. If i look into the \www\snapshots folder there is the new snapshot.

```yaml
action: advanced_snapshot.take_snapshot
data:
  camera_entity_id: camera.hofkamera_fliessend
  file_path: test.jpg
```
simple picture card
```yaml
type: picture
image: /lokal/snapshots/test.jpg
```
Maybe you know why i dont get the new one.
